### ISSUE TITLE
Printing wide charts causes cropping

### ISSUE THREAD

**Issue by marpstar** [amcharts/export#3]
We're trying to set up Print Export for a serial chart.  Seems that the chart is not resized before print, which causes charts to be cropped.

Is AmCharts assuming that we want to print in landscape? It seems that our charts are always fitting in landscape.

We followed directions at http://www.amcharts.com/tutorials/resizing-chart-for-print/, but that doesn't seem to have an effect for AmCharts 3.14

We noticed in `export.js` that the chart is added to the page with 100% width.  Could this be a customizable option, like PDF export, to fit a particular page size?

**Comment by maertz** [comment]
unfortunately the print events are not very stable across browsers, some might call them, others don't. That's why we added the alternate in our plugin, it's not possible to pass any options to the native print method but you can change it within the print modal which pops up from the browser or force it through CSS to set a default.

    <style type="text/css" media="print">
      @page { size: landscape; }
    </style>
