### ISSUE TITLE
PNG/JPG export is not working in Gantt chart in IE10

### ISSUE THREAD

**Issue by ksurakka** [amcharts/export#33]
Hello,

I'm not sure if this is an issue of export-library or fabric-library, but when trying to export Gantt chart to PNG with IE10, I get:
SCRIPT5022: SecurityError 
fabric.js, line 678 character 1

Can be tested in Amchart demo site: https://www.amcharts.com/demos/gantt-chart/

Best regards
  Kari S

**Comment by maertz** [comment]
Hi Kari,

that took a while, the IE10 seems to have an handling issue with the image origin of SVG images. They get misleadingly declared as "tainted" that's why it throws the SecurityError. Luckely we can simply disable the SVG icons to fallback to the PNG icons, therefore I would suggest you to disable [svgIcons](http://docs.amcharts.com/3/javascriptcharts/AmChart#svgIcons) in your chart setup to solve that.

**Comment by maertz** [comment]
Hi Kari, just to let you know that we've handled it within the export plugin as well.
We simply remove the SVG images to avoid such behaviour, if you want to keep those icons in IE10 use the svgIcons flag I've mentioned above.

Sincerely Ben
